# Generated by Django 5.2 on 2025-04-26 19:11

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao_escolar", "0015_anexoatendimento"),
    ]

    operations = [
        migrations.CreateModel(
            name="Avaliacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("Prova", "Prova"),
                            ("Seminário", "Seminário"),
                            ("Outras Atividades", "Outras Atividades"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "bimestre",
                    models.IntegerField(
                        choices=[
                            (1, "1º Bimestre"),
                            (2, "2º Bimestre"),
                            (3, "3º Bimestre"),
                            (4, "4º Bimestre"),
                        ]
                    ),
                ),
                ("data", models.DateField(default=datetime.date.today)),
                (
                    "disciplina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes",
                        to="gestao_escolar.disciplina",
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes",
                        to="gestao_escolar.turma",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NotaAvaliacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nota",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestao_escolar.aluno",
                    ),
                ),
                (
                    "avaliacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas_avaliacao",
                        to="gestao_escolar.avaliacao",
                    ),
                ),
            ],
        ),
    ]
