# Generated by Django 5.2 on 2025-04-26 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gestao_escolar", "0016_avaliacao_notaavaliacao"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="avaliacao",
            name="turma",
        ),
    ]
